DROP DATABASE CatalogoJogos;

DROP TABLE Jogos;

USE CatalogoJogos;

CREATE DATABASE CatalogoJogos;

CREATE TABLE Jogos
(
Id UNIQUEIDENTIFIER NOT NULL,
Nome VARCHAR(255) NOT NULL,
Produtora VARCHAR(255) NOT NULL,
Preco REAL NOT NULL,
Lancamento INT NOT NULL,
PRIMARY KEY (Id)
);